### ISSUE TITLE
Launchbox Does not update metadata

### ISSUE THREAD

**Issue by Bboy486** [spektor56/LBGDBPlaynitePlugin#5]
Settings > Library > Download Metadata: Only filters games
When it runs (I set Launchbox in position #1 in the settings for art) it does not update to the launchbox art. I have to manually select a game (one by one) edit download metadata for the art to update Edit > Download Meta > Launchbox

**Comment by spektor56** [comment]
I'm not having this issue.  Try the latest installable version, it does icons using the clear logos now

**Comment by Bboy486** [comment]
Thanks. I ended up removing launchbox as I couldn't get it to work.
