### ISSUE TITLE
Doesn't work on Playnite 8.x

### ISSUE THREAD

**Issue by notNSANE** [spektor56/LBGDBPlaynitePlugin#7]
Tried uninstalling and installing, changing stuff around but nothing happens. I use Edit... > Metadata > Launchbox, there'a very small refresh then it stops. It works correctly with Wikipedia or IGDB.

Tested on both playnite 8.2 and 8.3

**Comment by Zhiro90** [comment]
Confirmed still not working on 8.6

Edit: It does work by downloading the xml package first!

**Comment by spektor56** [comment]
Yes, the plugin doesn't come with the metadata pre-downloafed. you have to download and update it manually from the settings page for the plugin.  This is the way the launchbox API works, they update their file once a day so if you need the updated metadata you will have to trigger this process again.  I put a limit to only allow download when the metadata file has changed so the launchbox servers won't be killed
